// TỰ SINH bởi scripts/prepare-local.mjs từ thư mục migrations/ – đừng sửa tay.
export const MIGRATIONS: { name: string; sql: string }[] = [
  {
    "name": "0001_init.sql",
    "sql": "-- Giảng viên\nCREATE TABLE IF NOT EXISTS teachers (\n  id TEXT PRIMARY KEY,\n  name TEXT NOT NULL,\n  email TEXT,\n  phone TEXT,\n  department TEXT,\n  color TEXT NOT NULL DEFAULT '#60a5fa',\n  created_at TEXT NOT NULL DEFAULT (datetime('now'))\n);\n\n-- Phòng học\nCREATE TABLE IF NOT EXISTS rooms (\n  id TEXT PRIMARY KEY,\n  name TEXT NOT NULL,\n  building TEXT,\n  capacity INTEGER,\n  equipment TEXT,\n  created_at TEXT NOT NULL DEFAULT (datetime('now'))\n);\n\n-- Buổi giảng (date: YYYY-MM-DD, time: HH:MM)\nCREATE TABLE IF NOT EXISTS sessions (\n  id TEXT PRIMARY KEY,\n  series_id TEXT,\n  title TEXT NOT NULL,\n  class_name TEXT,\n  teacher_id TEXT NOT NULL REFERENCES teachers(id),\n  room_id TEXT NOT NULL REFERENCES rooms(id),\n  date TEXT NOT NULL,\n  start_time TEXT NOT NULL,\n  end_time TEXT NOT NULL,\n  note TEXT,\n  status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'cancelled')),\n  created_at TEXT NOT NULL DEFAULT (datetime('now'))\n);\n\nCREATE INDEX IF NOT EXISTS idx_sessions_date ON sessions(date);\nCREATE INDEX IF NOT EXISTS idx_sessions_teacher_date ON sessions(teacher_id, date);\nCREATE INDEX IF NOT EXISTS idx_sessions_room_date ON sessions(room_id, date);\nCREATE INDEX IF NOT EXISTS idx_sessions_series ON sessions(series_id);\n"
  },
  {
    "name": "0002_templates.sql",
    "sql": "-- Loại lịch: lecture | practice | meeting | seminar | exam | defense | office_hours | other\nALTER TABLE sessions ADD COLUMN kind TEXT NOT NULL DEFAULT 'lecture';\nCREATE INDEX IF NOT EXISTS idx_sessions_kind_date ON sessions(kind, date);\n\n-- Mẫu lịch: người dùng chọn để điền sẵn form đặt lịch\nCREATE TABLE IF NOT EXISTS templates (\n  id TEXT PRIMARY KEY,\n  name TEXT NOT NULL,\n  kind TEXT NOT NULL DEFAULT 'meeting',\n  icon TEXT,\n  title TEXT,\n  duration_minutes INTEGER NOT NULL DEFAULT 60,\n  start_time TEXT,\n  repeat_weeks INTEGER NOT NULL DEFAULT 1,\n  teacher_id TEXT REFERENCES teachers(id) ON DELETE SET NULL,\n  room_id TEXT REFERENCES rooms(id) ON DELETE SET NULL,\n  note TEXT,\n  sort_order INTEGER NOT NULL DEFAULT 0,\n  created_at TEXT NOT NULL DEFAULT (datetime('now'))\n);\n\nINSERT OR IGNORE INTO templates (id, name, kind, icon, title, duration_minutes, start_time, repeat_weeks, note, sort_order) VALUES\n  ('tpl-lecture', 'Buổi giảng lý thuyết', 'lecture', '📚', NULL, 120, '07:00', 15, NULL, 10),\n  ('tpl-practice', 'Thực hành / Lab', 'practice', '🧪', NULL, 180, '13:00', 15, 'Chuẩn bị: máy tính, tài liệu thực hành', 20),\n  ('tpl-dept-meeting', 'Họp bộ môn', 'meeting', '👥', 'Họp bộ môn', 90, '14:00', 1,\n   'Nội dung:\n1. Báo cáo tiến độ giảng dạy\n2. Kế hoạch chuyên môn tháng tới\n3. Ý kiến khác', 30),\n  ('tpl-faculty-meeting', 'Họp khoa', 'meeting', '🏛️', 'Họp khoa', 120, '08:00', 1,\n   'Thành phần: toàn thể cán bộ, giảng viên\nNội dung:\n1. Thông báo của Ban chủ nhiệm khoa\n2. Tổng kết công tác\n3. Thảo luận', 40),\n  ('tpl-seminar', 'Seminar khoa học', 'seminar', '🎤', 'Seminar khoa học', 90, '15:00', 1,\n   'Báo cáo viên:\nChủ đề:\nThời gian trình bày 45 phút, thảo luận 30 phút', 50),\n  ('tpl-exam', 'Coi thi', 'exam', '📝', 'Coi thi', 90, '07:30', 1,\n   'Có mặt trước giờ thi 15 phút. Mang theo thẻ cán bộ.', 60),\n  ('tpl-defense', 'Bảo vệ luận văn / đồ án', 'defense', '🎓', 'Bảo vệ đồ án tốt nghiệp', 180, '08:00', 1,\n   'Hội đồng:\n- Chủ tịch:\n- Thư ký:\n- Phản biện:\nDanh sách sinh viên:', 70),\n  ('tpl-office-hours', 'Tiếp sinh viên', 'office_hours', '💬', 'Giờ tiếp sinh viên', 60, '16:00', 15, NULL, 80);\n"
  },
  {
    "name": "0003_participants_auth.sql",
    "sql": "-- Người tham dự (ngoài người chủ trì sessions.teacher_id)\nCREATE TABLE IF NOT EXISTS session_participants (\n  session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,\n  teacher_id TEXT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,\n  PRIMARY KEY (session_id, teacher_id)\n);\nCREATE INDEX IF NOT EXISTS idx_participants_teacher ON session_participants(teacher_id);\n\n-- Tài khoản đăng nhập. role: admin | teacher (teacher liên kết với một giảng viên)\nCREATE TABLE IF NOT EXISTS users (\n  id TEXT PRIMARY KEY,\n  username TEXT NOT NULL UNIQUE COLLATE NOCASE,\n  display_name TEXT NOT NULL,\n  password_hash TEXT NOT NULL,\n  role TEXT NOT NULL DEFAULT 'teacher',\n  teacher_id TEXT REFERENCES teachers(id) ON DELETE SET NULL,\n  created_at TEXT NOT NULL DEFAULT (datetime('now'))\n);\n\n-- Phiên đăng nhập: chỉ lưu SHA-256 của token trong cookie\nCREATE TABLE IF NOT EXISTS auth_sessions (\n  token_hash TEXT PRIMARY KEY,\n  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  expires_at TEXT NOT NULL,\n  created_at TEXT NOT NULL DEFAULT (datetime('now'))\n);\nCREATE INDEX IF NOT EXISTS idx_auth_sessions_user ON auth_sessions(user_id);\n\n-- Chống dò mật khẩu: đếm số lần đăng nhập sai theo tên đăng nhập\nCREATE TABLE IF NOT EXISTS login_attempts (\n  username TEXT PRIMARY KEY,\n  failures INTEGER NOT NULL DEFAULT 0,\n  window_start TEXT NOT NULL\n);\n"
  },
  {
    "name": "0004_settings.sql",
    "sql": "-- Cài đặt chung của đơn vị (key/value). profile: education | business | office\nCREATE TABLE IF NOT EXISTS settings (\n  key TEXT PRIMARY KEY,\n  value TEXT NOT NULL\n);\n-- Bản cài đặt đã có dữ liệu trước đây là trường học\nINSERT OR IGNORE INTO settings (key, value) VALUES ('profile', 'education'), ('org_name', '');\n\n-- Phòng ảo (Online, Bên ngoài / Công tác): không kiểm tra trùng phòng, chỉ kiểm tra trùng người\nALTER TABLE rooms ADD COLUMN is_virtual INTEGER NOT NULL DEFAULT 0;\nINSERT OR IGNORE INTO rooms (id, name, building, capacity, equipment, is_virtual) VALUES\n  ('r-online', 'Online', NULL, NULL, 'Google Meet / Zoom / Teams', 1),\n  ('r-outside', 'Bên ngoài / Công tác', NULL, NULL, NULL, 1);\n"
  }
];
